/**
 * A browser-side port of the Weng-Lin models as implemented in OpenSkill
 * (github.com/vivekjoshy/openskill.py), for the interactive playground.
 *
 * Ported directly from the Python source, not reconstructed from the paper.
 * Verified against reference vectors generated by openskill itself; see
 * `scripts/verify-openskill.mjs`, which fails the build on divergence.
 *
 * Defaults match the library: mu=25, sigma=25/3, beta=25/6, tau=25/300,
 * kappa=1e-4, epsilon=0.1, with balance/limit_sigma off.
 */

export interface Rating {
  mu: number
  sigma: number
}

export type ModelName = 'plackett_luce' | 'thurstone_mosteller' | 'bradley_terry'

export const DEFAULTS = {
  mu: 25.0,
  sigma: 25.0 / 3.0,
  beta: 25.0 / 6.0,
  tau: 25.0 / 300.0,
  kappa: 0.0001,
  epsilon: 0.1
}

/* ------------------------------------------------------------------ */
/* Normal distribution helpers                                         */
/* ------------------------------------------------------------------ */

/** Abramowitz & Stegun 7.1.26; max absolute error ~1.5e-7. */
function erf(x: number): number {
  const sign = x < 0 ? -1 : 1
  const ax = Math.abs(x)
  const a1 = 0.254829592
  const a2 = -0.284496736
  const a3 = 1.421413741
  const a4 = -1.453152027
  const a5 = 1.061405429
  const p = 0.3275911
  const t = 1 / (1 + p * ax)
  const y = 1 - ((((a5 * t + a4) * t + a3) * t + a2) * t + a1) * t * Math.exp(-ax * ax)
  return sign * y
}

/** Normal CDF. */
export function phiMajor(x: number): number {
  return 0.5 * (1 + erf(x / Math.SQRT2))
}

/** Normal PDF. */
export function phiMinor(x: number): number {
  return Math.exp(-0.5 * x * x) / Math.sqrt(2 * Math.PI)
}

const EPS = Number.EPSILON

function v(x: number, t: number): number {
  const xt = x - t
  const denom = phiMajor(xt)
  return denom < EPS ? -xt : phiMinor(xt) / denom
}

function w(x: number, t: number): number {
  const xt = x - t
  const denom = phiMajor(xt)
  if (denom < EPS) return x < 0 ? 1 : 0
  const vv = v(x, t)
  return vv * (vv + xt)
}

function vt(x: number, t: number): number {
  const xx = Math.abs(x)
  const b = phiMajor(t - xx) - phiMajor(-t - xx)
  if (b < 1e-5) return x < 0 ? -x - t : -x + t
  const a = phiMinor(-t - xx) - phiMinor(t - xx)
  return (x < 0 ? -a : a) / b
}

function wt(x: number, t: number): number {
  const xx = Math.abs(x)
  const b = phiMajor(t - xx) - phiMajor(-t - xx)
  if (b < EPS) return 1.0
  const vv = vt(x, t)
  return ((t - xx) * phiMinor(t - xx) + (t + xx) * phiMinor(-t - xx)) / b + vv * vv
}

/* ------------------------------------------------------------------ */
/* Team aggregation                                                    */
/* ------------------------------------------------------------------ */

interface TeamRating {
  mu: number
  sigmaSquared: number
  team: Rating[]
  rank: number
}

/** Dense 0-based ranks, matching `_calculate_rankings`. */
function calculateRankings(ranks: number[]): number[] {
  const sorted = [...ranks].sort((a, b) => a - b)
  const rankMap = new Map<number, number>()
  sorted.forEach((value, index) => {
    if (!rankMap.has(value)) rankMap.set(value, index)
  })
  return ranks.map((r) => rankMap.get(r) as number)
}

function calculateTeamRatings(teams: Rating[][], ranks: number[]): TeamRating[] {
  const dense = calculateRankings(ranks)
  return teams.map((team, index) => {
    let mu = 0
    let sigmaSquared = 0
    for (const p of team) {
      mu += p.mu
      sigmaSquared += p.sigma * p.sigma
    }
    return { mu, sigmaSquared, team, rank: dense[index] as number }
  })
}

/** Apply tau to sigma before rating, as `rate()` does. */
function applyTau(teams: Rating[][], tau: number): Rating[][] {
  const tauSq = tau * tau
  return teams.map((t) => t.map((p) => ({ mu: p.mu, sigma: Math.sqrt(p.sigma * p.sigma + tauSq) })))
}

/** Shared per-player update. `balance` and weights are off, so weight is 1. */
function applyUpdate(tr: TeamRating, omega: number, delta: number, kappa: number): Rating[] {
  return tr.team.map((p) => {
    const sigmaSq = p.sigma * p.sigma
    const share = sigmaSq / tr.sigmaSquared
    const mu = p.mu + share * omega
    const sigma = p.sigma * Math.sqrt(Math.max(1 - share * delta, kappa))
    return { mu, sigma }
  })
}

/* ------------------------------------------------------------------ */
/* Plackett-Luce                                                       */
/* ------------------------------------------------------------------ */

function ratePlackettLuce(teams: Rating[][], ranks: number[]): Rating[][] {
  const { beta, kappa } = DEFAULTS
  const teamRatings = calculateTeamRatings(teams, ranks)

  let collective = 0
  for (const t of teamRatings) collective += t.sigmaSquared + beta * beta
  const c = Math.sqrt(collective)

  // sum_q[q] = sum of exp(mu_i / c) over teams i with rank_i >= rank_q
  const sumQ = new Array(teamRatings.length).fill(0)
  for (const teamI of teamRatings) {
    const summed = Math.exp(teamI.mu / c)
    teamRatings.forEach((teamQ, q) => {
      if (teamI.rank >= teamQ.rank) sumQ[q] += summed
    })
  }

  // a[q] = number of teams sharing rank_q
  const a = teamRatings.map((i) => teamRatings.filter((q) => q.rank === i.rank).length)

  return teamRatings.map((teamI, i) => {
    let omega = 0
    let delta = 0
    const iMuOverC = Math.exp(teamI.mu / c)

    teamRatings.forEach((teamQ, q) => {
      const quotient = iMuOverC / sumQ[q]
      if (teamQ.rank <= teamI.rank) {
        delta += (quotient * (1 - quotient)) / a[q]
        omega += q === i ? (1 - quotient) / a[q] : -quotient / a[q]
      }
    })

    omega *= teamI.sigmaSquared / c
    delta *= teamI.sigmaSquared / (c * c)
    delta *= Math.sqrt(teamI.sigmaSquared) / c // gamma

    return applyUpdate(teamI, omega, delta, kappa)
  })
}

/* ------------------------------------------------------------------ */
/* Thurstone-Mosteller Full                                            */
/* ------------------------------------------------------------------ */

function rateThurstoneMosteller(teams: Rating[][], ranks: number[]): Rating[][] {
  const { beta, kappa, epsilon } = DEFAULTS
  const teamRatings = calculateTeamRatings(teams, ranks)

  return teamRatings.map((teamI, i) => {
    let omega = 0
    let delta = 0

    teamRatings.forEach((teamQ, q) => {
      if (q === i) return
      const cIq = Math.sqrt(teamI.sigmaSquared + teamQ.sigmaSquared + 2 * beta * beta)
      const deltaMu = (teamI.mu - teamQ.mu) / cIq
      const sigmaSqToCiq = teamI.sigmaSquared / cIq
      const gamma = Math.sqrt(teamI.sigmaSquared) / cIq
      const epsOverCiq = epsilon / cIq

      if (teamQ.rank > teamI.rank) {
        omega += sigmaSqToCiq * v(deltaMu, epsOverCiq)
        delta += ((gamma * sigmaSqToCiq) / cIq) * w(deltaMu, epsOverCiq)
      } else if (teamQ.rank < teamI.rank) {
        omega += -sigmaSqToCiq * v(-deltaMu, epsOverCiq)
        delta += ((gamma * sigmaSqToCiq) / cIq) * w(-deltaMu, epsOverCiq)
      } else {
        omega += sigmaSqToCiq * vt(deltaMu, epsOverCiq)
        delta += ((gamma * sigmaSqToCiq) / cIq) * wt(deltaMu, epsOverCiq)
      }
    })

    return applyUpdate(teamI, omega, delta, kappa)
  })
}

/* ------------------------------------------------------------------ */
/* Bradley-Terry Full                                                  */
/* ------------------------------------------------------------------ */

function rateBradleyTerry(teams: Rating[][], ranks: number[]): Rating[][] {
  const { beta, kappa } = DEFAULTS
  const teamRatings = calculateTeamRatings(teams, ranks)

  return teamRatings.map((teamI, i) => {
    let omega = 0
    let delta = 0

    teamRatings.forEach((teamQ, q) => {
      if (q === i) return
      const cIq = Math.sqrt(teamI.sigmaSquared + teamQ.sigmaSquared + 2 * beta * beta)
      const piq = 1 / (1 + Math.exp((teamQ.mu - teamI.mu) / cIq))
      const sigmaSqToCiq = teamI.sigmaSquared / cIq
      const gamma = Math.sqrt(teamI.sigmaSquared) / cIq

      let s = 0
      if (teamQ.rank > teamI.rank) s = 1.0
      else if (teamQ.rank === teamI.rank) s = 0.5

      omega += sigmaSqToCiq * (s - piq)
      delta += ((gamma * sigmaSqToCiq) / cIq) * piq * (1 - piq)
    })

    return applyUpdate(teamI, omega, delta, kappa)
  })
}

/* ------------------------------------------------------------------ */
/* Public API                                                          */
/* ------------------------------------------------------------------ */

/**
 * Update ratings from a result. `ranks` is 1-based and ascending, so
 * `[1, 2]` means the first team won. Equal values are a draw.
 */
export function rate(teams: Rating[][], ranks: number[], model: ModelName = 'plackett_luce'): Rating[][] {
  const withTau = applyTau(teams, DEFAULTS.tau)
  if (model === 'thurstone_mosteller') return rateThurstoneMosteller(withTau, ranks)
  if (model === 'bradley_terry') return rateBradleyTerry(withTau, ranks)
  return ratePlackettLuce(withTau, ranks)
}

/** Win probability per team. Two-team case is exact; n-team is the pairwise generalization. */
export function predictWin(teams: Rating[][]): number[] {
  const { beta } = DEFAULTS
  const agg = teams.map((team) => {
    let mu = 0
    let sigmaSquared = 0
    for (const p of team) {
      mu += p.mu
      sigmaSquared += p.sigma * p.sigma
    }
    return { mu, sigmaSquared }
  })

  if (agg.length === 2) {
    const [a, b] = agg as [{ mu: number; sigmaSquared: number }, { mu: number; sigmaSquared: number }]
    const p = phiMajor((a.mu - b.mu) / Math.sqrt(2 * beta * beta + a.sigmaSquared + b.sigmaSquared))
    return [p, 1 - p]
  }

  const n = agg.length
  const pairwise: number[] = []
  for (let i = 0; i < n; i++) {
    for (let j = 0; j < n; j++) {
      if (i === j) continue
      const x = agg[i] as { mu: number; sigmaSquared: number }
      const y = agg[j] as { mu: number; sigmaSquared: number }
      pairwise.push(phiMajor((x.mu - y.mu) / Math.sqrt(2 * beta * beta + x.sigmaSquared + y.sigmaSquared)))
    }
  }

  const raw: number[] = []
  for (let i = 0; i < n; i++) {
    let s = 0
    for (let j = i * (n - 1); j < (i + 1) * (n - 1); j++) s += pairwise[j] as number
    raw.push(s / (n - 1))
  }
  const total = raw.reduce((x, y) => x + y, 0)
  return raw.map((p) => p / total)
}

/** Conservative skill estimate: mu - z*sigma. */
export function ordinal(r: Rating, z = 3.0): number {
  return r.mu - z * r.sigma
}

export function newRating(mu = DEFAULTS.mu, sigma = DEFAULTS.sigma): Rating {
  return { mu, sigma }
}
